#!/usr/bin/env ruby
# frozen_string_literal: true

require "rubygems"
require "bundler/setup"

require "active_support"
require "pry"

require_relative "./configuration"
require_relative "./factory"
require_relative "./app"

config  = Tracing::Configuration.parse!
factory = Tracing::Factory.new(config)
app     = Tracing::App.new(config, factory)
app.run!

